name : Unit Test
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - master
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.6'
      - run: go test -v -cover ./testing/...